src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Notify_of_Upcoming_Trainings__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This potential volunteer has requested to be notified of upcoming trainings.</description>
        <inlineHelpText>This potential volunteer has requested to be notified of upcoming trainings.</inlineHelpText>
        <label>Notify of Upcoming Trainings</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Volunteer_Training__c.object
<CustomObject>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VolunteerService.cls
/**
 * @author John Schultz
 * @date 2017-11-08
 *
 * @description Service layer for working with volunteers (contacts)
 */
public class VolunteerService {
    
    /**
     * @description Method for registering a new volunteer and setting them up
     * with a training attendance.
     *
     * @param con
     * @param trainingId
     */
    public static void registerNewVolunteer(Contact con, String trainingId) {
        Contact existingContact;
        Volunteer_Training_Attendance__c vta;
        
        // first check to see if a contact already exists with that phone number
        existingContact = findByPhone(con.Phone);
        
        if (existingContact != null) {
            con.Id = existingContact.Id;
        }
        
        con.Notify_of_Upcoming_Trainings__c = (String.isBlank(trainingId) ||
            trainingId == 'X');
        
        // upsert contact and details
        upsert con;
        
        // if a training id was provided, create a new corresponding training
        // attendance record.
        if (String.isNotBlank(trainingId) && trainingId != 'X') {
            vta = new Volunteer_Training_Attendance__c(
                Volunteer__c = con.Id,
                Volunteer_Training__c = trainingId
            );
            
            insert vta;
        }
    }
    
    /**
     * @description Retrieves contact by phone number.
     *
     * @param phone
     *
     * @return Contact
     */
    public static Contact findByPhone(String phone) {
        Contact c;
        
        List<Contact> results = new List<Contact>([
            SELECT
                Id
            FROM Contact
            WHERE Phone = :phone
            LIMIT 1
        ]);
        
        if (!results.isEmpty()) {
            c = results[0];
        }
        
        return c;
    }
}