src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Allowed_to_Volunteer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this contact is allowed to volunteer and has completed all necessary paperwork, training, tasks, etc.</description>
        <inlineHelpText>If checked, this contact is allowed to volunteer and has completed all necessary paperwork, training, tasks, etc.</inlineHelpText>
        <label>Allowed to Volunteer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facilitator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Does this person ever work at Encircle in the role of Facilitator?</description>
        <inlineHelpText>Does this person ever work at Encircle in the role of Facilitator?</inlineHelpText>
        <label>Facilitator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_of_Upcoming_Trainings__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This potential volunteer has requested to be notified of upcoming trainings.</description>
        <inlineHelpText>This potential volunteer has requested to be notified of upcoming trainings.</inlineHelpText>
        <label>Notify of Upcoming Trainings</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VolunteerService_TEST.cls
@IsTest
private class VolunteerService_TEST {
    
    private static Contact con;
    private static Contact facilitator;
    private static String phone;
    
    static {
        phone = '8568484606';
        
        con = new Contact(
            FirstName = 'testing',
            LastName = 'lastName',
            Phone = phone,
            Allowed_to_Volunteer__c = true,
            Volunteer__c = true
        );
        
        facilitator = new Contact(
            FirstName = 'Facilitator',
            LastName = 'Facilitator',
            Phone = '6064848658',
            Facilitator__c = true
        );
    }
    
    static testMethod void testRegistration() {
        VolunteerService service = VolunteerService.getInstance();
        Volunteer_Training__c training = new Volunteer_Training__c(
            StartDateTime__c = Datetime.now()
        );
        insert training;
        
        
        Test.startTest();
        
        service.registerNewVolunteer(con, null);
        
        Contact conTest1 = [
            SELECT
                Id,
                FirstName,
                LastName,
                Notify_of_Upcoming_Trainings__c
            FROM Contact
            WHERE Phone = :phone
        ];
    
        System.assertEquals(con.FirstName, conTest1.FirstName);
        System.assertEquals(con.LastName, conTest1.LastName);
        System.assertEquals(false, conTest1.Notify_of_Upcoming_Trainings__c);
        
        // testing update on existing
        con.FirstName = 'newFirst';
        service.registerNewVolunteer(con, 'X');
    
        Contact conTest2 = [
            SELECT
                Id,
                FirstName,
                Notify_of_Upcoming_Trainings__c
            FROM Contact
            WHERE Id = :con.Id
        ];
    
        System.assertEquals(con.FirstName, conTest2.FirstName);
        System.assertEquals(true, conTest2.Notify_of_Upcoming_Trainings__c);
        
        // testing update on existing with training attendance
        service.registerNewVolunteer(con, training.Id);
        
        Contact conTest3 = [
            SELECT
                Id,
                Notify_of_Upcoming_Trainings__c
            FROM Contact
            WHERE Id = :con.Id
        ];
    
        System.assertEquals(false, conTest3.Notify_of_Upcoming_Trainings__c);
        
        Volunteer_Training_Attendance__c vta = [
            SELECT
                Volunteer__c,
                Volunteer_Training__c
            FROM Volunteer_Training_Attendance__c
            LIMIT 1
        ];
    
        System.assertEquals(training.Id, vta.Volunteer_Training__c);
        System.assertEquals(con.Id, vta.Volunteer__c);
        
        Test.stopTest();
    }
    
    static testMethod void testFuzzySearch() {
        VolunteerService service = VolunteerService.getInstance();
        insert new List<Contact>{con, facilitator};
        
        Test.startTest();
        
        // testing for no results
        List<Contact> noResults = service.findContactByFuzzyNameSearch('xxxx');
        System.assertEquals(0, noResults.size());
        
        // testing for positive results
        List<Contact> hasResults = service.findContactByFuzzyNameSearch('tes las');
        System.assertEquals(1, hasResults.size());
        List<Contact> facilitators = service.findFacilitatorByFuzzyNameSearch('Facilitator');
        System.assertEquals(1, facilitators.size());
        
        Test.stopTest();
    }
}