src/objects/Door_Activity__c.object
<CustomObject>
    <description>Object used to track how many people come through the front door and why they are here.</description>
    <fields>
        <fullName>X3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>3am</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Door Activity</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Door Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DoorSurveyController_TEST.cls
@IsTest
private class DoorSurveyController_TEST {
    
    static testMethod void testVisitors() {
        Test.startTest();
        
        List<String> visitorTypes = DoorSurveyController.getVisitorTypes();
        System.assertNotEquals(0, visitorTypes.size());
        
        DoorSurveyController.saveActivity(visitorTypes[0], '2020-10-25', '3');
        List<Door_Activity__c> activities = new List<Door_Activity__c>([SELECT Id, X3__c FROM Door_Activity__c]);
        System.assertEquals(1, activities.size());
        System.assertEquals(1, activities[0].X3__c);
        
        Test.stopTest();
    }
    
}