src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VolTrainingAttendanceTriggerHandler.cls
public class VolTrainingAttendanceTriggerHandler extends TriggerHandler {
    
    private List<Volunteer_Training_Attendance__c> newList;
    private Map<Id, Volunteer_Training_Attendance__c> newMap;
    private Map<Id, Volunteer_Training_Attendance__c> oldMap;
    
    public VolTrainingAttendanceTriggerHandler() {
        this.newList = (List<Volunteer_Training_Attendance__c>) Trigger.new;
        this.newMap = (Map<Id, Volunteer_Training_Attendance__c>) Trigger.newMap;
        
        this.oldMap = Trigger.oldMap != null ?
            (Map<Id, Volunteer_Training_Attendance__c>) Trigger.oldMap :
            new Map<Id, Volunteer_Training_Attendance__c>();
    }
    
    public override void beforeInsert() {
        this.updateStartDate();
    }
    
    public override void beforeUpdate() {
        this.updateStartDate();
    }
    
    /**
     * @description This method will look at the attendance records to see if
     * they are new or if they've been reparented to a different training
     * record. If so, the attendance record's StartDateTime__c field will be
     * updated to match the current parent training record.
     */
    private void updateStartDate() {
        Map<Id, Volunteer_Training__c> trainings;
        Set<String> trainingIds = new Set<String>();
        List<Volunteer_Training_Attendance__c> vtasToUpdate =
            new List<Volunteer_Training_Attendance__c>();
        
        // check for new records or changes.
        for (Volunteer_Training_Attendance__c newVta : this.newList) {
            if (newVta.Volunteer_Training__c != null && (
                Trigger.isInsert ||
                newVta.Volunteer_Training__c != this.oldMap.get(newVta.Id).Volunteer_Training__c
            )) {
                
                trainingIds.add(newVta.Volunteer_Training__c);
                vtasToUpdate.add(newVta);
            }
        }
        
        // get the parent training records.
        if (!trainingIds.isEmpty() && !vtasToUpdate.isEmpty()) {
            trainings = new Map<Id, Volunteer_Training__c>(
                TrainingService.getTrainingsById(trainingIds)
            );
        }
        
        // update the attendance records that need to be updated.
        if (trainings != null && !trainings.isEmpty()) {
            for (Volunteer_Training_Attendance__c vta : vtasToUpdate) {
                vta.StartDateTime__c = trainings.get(vta.Volunteer_Training__c).StartDateTime__c;
            }
        }
    }
}