src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>The date and time when this training is expected to end.</description>
        <inlineHelpText>The date and time when this training is expected to end.</inlineHelpText>
        <label>End Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location where this training will take place.</description>
        <inlineHelpText>The location where this training will take place.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Training__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks if the volunteer attended and completed the training. If checked, the volunteer showed up and completed the training. If unchecked, the volunteer signed up but never completed the training.</description>
        <inlineHelpText>Did this volunteer attend and complete this training? If checked, the volunteer showed up and completed the training. If unchecked, the volunteer signed up but never completed the training.</inlineHelpText>
        <label>Completed Training</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VolunteerTrainingViewModel.cls
public class VolunteerTrainingViewModel {
    @AuraEnabled
    public Id id;
    @AuraEnabled
    public Datetime startDateTime;
    @AuraEnabled
    public Datetime endDateTime;
    @AuraEnabled
    public String location;
    @AuraEnabled
    public String description;
    public Boolean completed;
    public Id trainingId;
    public Id volunteerId;
    
    public VolunteerTrainingViewModel() {}
    
    public VolunteerTrainingViewModel(Volunteer_Training__c vt) {
        id = vt.Id;
        startDateTime = vt.StartDateTime__c;
        endDateTime = vt.EndDateTime__c;
        location = vt.Location__c;
        description = vt.Description__c;
    }
    
    public VolunteerTrainingViewModel(Volunteer_Training_Attendance__c vta) {
        id = vta.Id;
        startDateTime = vta.Volunteer_Training__r.StartDateTime__c;
        endDateTime = vta.Volunteer_Training__r.EndDateTime__c;
        location = vta.Volunteer_Training__r.Location__c;
        description = vta.Volunteer_Training__r.Description__c;
        completed = vta.Completed_Training__c;
        trainingId = vta.Volunteer_Training__c;
        volunteerId = vta.Volunteer__c;
    }
}