src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VTTriggerHandler_TEST.cls
@IsTest
private class VTTriggerHandler_TEST {
    
    private static testMethod void testChangedDate() {
        Contact con = new Contact(
            FirstName = 'testVTTriggerHandler_TEST',
            LastName = 'testVTTriggerHandler_TEST'
        );
        insert con;
        
        Volunteer_Training__c training = new Volunteer_Training__c(
            StartDateTime__c = Datetime.now()
        );
        insert training;
        
        Volunteer_Training_Attendance__c vta = new Volunteer_Training_Attendance__c(
            Volunteer_Training__c = training.Id,
            Volunteer__c = con.Id
        );
        insert vta;
        
        Test.startTest();
        
        training.StartDateTime__c = Datetime.now().addDays(2);
        update training;
        
        Test.stopTest();
        
        Volunteer_Training_Attendance__c testVta = [
            SELECT
                Id,
                StartDateTime__c
            FROM Volunteer_Training_Attendance__c
            WHERE Id = :vta.Id
        ];
    
        System.assertEquals(training.StartDateTime__c, testVta.StartDateTime__c);
    }
}