src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location where this training will take place.</description>
        <inlineHelpText>The location where this training will take place.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrainingModel.cls
/**
 * @author John Schultz
 * @date 2017-11-08
 * @description Model for volunteer trainings.
 */
public class TrainingModel {
    @AuraEnabled public Id id;
    @AuraEnabled public String name;
    @AuraEnabled public String detailedName;
    
    public TrainingModel(Volunteer_Training__c training) {
        this.id = training.Id;
        this.name = training.Name;
        this.detailedName = training.StartDateTime__c != null ?
            training.StartDateTime__c.format('MMMM d, h:mm a') : training.Name;
        
        if (String.isNotBlank(training.Location__c)) {
            this.detailedName += ' at ' + training.Location__c;
        }
    }
}