src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VTATriggerHandler_TEST.cls
@IsTest
private class VTATriggerHandler_TEST {
    
    private static testMethod void testDateChange() {
        Contact con = new Contact(
            FirstName = 'testVTTriggerHandler_TEST',
            LastName = 'testVTTriggerHandler_TEST'
        );
        insert con;
    
        Volunteer_Training__c training1 = new Volunteer_Training__c(
            StartDateTime__c = Datetime.now()
        );
        Volunteer_Training__c training2 = new Volunteer_Training__c(
            StartDateTime__c = Datetime.now()
        );
        insert new List<Volunteer_Training__c>{training1, training2};
    
        Volunteer_Training_Attendance__c vta = new Volunteer_Training_Attendance__c(
            Volunteer_Training__c = training1.Id,
            Volunteer__c = con.Id
        );
        insert vta;
        
        Volunteer_Training_Attendance__c test1 = [
            SELECT StartDateTime__c
            FROM Volunteer_Training_Attendance__c
            WHERE Id = :vta.Id
        ];
        
        // test beforeInsert
        System.assertEquals(training1.StartDateTime__c, test1.StartDateTime__c);
        
        // test reparenting
        vta.Volunteer_Training__c = training2.Id;
        update vta;
    
        Volunteer_Training_Attendance__c test2 = [
            SELECT StartDateTime__c
            FROM Volunteer_Training_Attendance__c
            WHERE Id = :vta.Id
        ];
        
        System.assertEquals(training2.StartDateTime__c, test2.StartDateTime__c);
    }
}