src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrainingService_TEST.cls
@IsTest
private class TrainingService_TEST {

    static testMethod void testUpcomingTrainings() {
        Volunteer_Training__c training1 = new Volunteer_Training__c(
            StartDateTime__c = Datetime.now().addDays(1)
        );
        Volunteer_Training__c training2 = new Volunteer_Training__c(
            StartDateTime__c = Datetime.now().addDays(-1)
        );
        insert new List<Volunteer_Training__c>{training1, training2};
    
        Test.startTest();
    
        List<TrainingModel> trainings = TrainingService.getUpcomingTrainings();
        System.assertEquals(1, trainings.size());
        System.assertEquals(training1.Id, trainings[0].id);
    
        Test.stopTest();
    }
}