src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>The date and time when this training is expected to end.</description>
        <inlineHelpText>The date and time when this training is expected to end.</inlineHelpText>
        <label>End Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location where this training will take place.</description>
        <inlineHelpText>The location where this training will take place.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VolunteerTrainingMapper_TEST.cls
@IsTest
private class VolunteerTrainingMapper_TEST {
    
    @IsTest
    private static void testQueries() {
        Volunteer_Training__c t1 = new Volunteer_Training__c(
            Description__c = 'testing',
            Location__c = 'my location',
            StartDateTime__c = Datetime.now().addDays(1),
            EndDateTime__c = Datetime.now().addDays(1).addMinutes(30)
        );
    
        Volunteer_Training__c t2 = new Volunteer_Training__c(
            Description__c = 'testing 2',
            Location__c = 'other location',
            StartDateTime__c = Datetime.now().addDays(1).addHours(1),
            EndDateTime__c = Datetime.now().addDays(1).addHours(1).addMinutes(30)
        );
    
        Volunteer_Training__c t3 = new Volunteer_Training__c(
            Description__c = 'testing old',
            Location__c = 'my location',
            StartDateTime__c = Datetime.now().addDays(-1),
            EndDateTime__c = Datetime.now().addDays(-1).addMinutes(30)
        );
        
        insert new List<Volunteer_Training__c>{t1, t2, t3};
        
        VolunteerTrainingMapper mapper = VolunteerTrainingMapper.getInstance();
        
        List<VolunteerTrainingViewModel> test1 = mapper.getUpcomingTrainings();
        System.assertEquals(2, test1.size());
        System.assertEquals(t1.Description__c, test1[0].description);
        
        List<VolunteerTrainingViewModel> test2 = mapper.getUpcomingTrainingsByLocation(t1.Location__c);
        System.assertEquals(1, test2.size());
    }

}