src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>The date and time when this training is expected to end.</description>
        <inlineHelpText>The date and time when this training is expected to end.</inlineHelpText>
        <label>End Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location where this training will take place.</description>
        <inlineHelpText>The location where this training will take place.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VolunteerTrainingMapper.cls
public virtual without sharing class VolunteerTrainingMapper {
    
    @TestVisible
    private static VolunteerTrainingMapper instance;
    
    protected VolunteerTrainingMapper() { }
    
    public static VolunteerTrainingMapper getInstance() {
        if (instance != null) {
            return instance;
        }
        
        instance = new VolunteerTrainingMapper();
        return instance;
    }
    
    public virtual List<VolunteerTrainingViewModel> getUpcomingTrainings() {
        return getUpcomingTrainingsByLocation(null);
    }
    
    public virtual List<VolunteerTrainingViewModel> getUpcomingTrainingsByLocation(String location) {
        String whereClause = '';
        
        whereClause += ' WHERE StartDateTime__c > ' +
            Datetime.now().format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'') + ' ';
        
        if (String.isNotBlank(location)) {
            whereClause += ' AND Location__c=\'' + location + '\' ';
        }
        
        return queryTrainings(whereClause);
    }
    
    private List<VolunteerTrainingViewModel> queryTrainings(String whereClause) {
        List<VolunteerTrainingViewModel> trainings;
        
        List<String> fields = new List<String>{
            'Id',
            'Description__c',
            'EndDateTime__c',
            'Location__c',
            'StartDateTime__c'
        };
        
        String queryString = String.format(
            'SELECT {0} FROM Volunteer_Training__c ',
            new List<String>{String.join(fields, ', ')}
        );
        
        if (String.isNotBlank(whereClause)) {
            queryString += whereClause;
        }
        
        queryString += ' ORDER BY StartDateTime__c ASC ';
        
        for (Volunteer_Training__c t : Database.query(queryString)) {
            if (trainings == null) {
                trainings = new List<VolunteerTrainingViewModel>();
            }
            
            trainings.add(new VolunteerTrainingViewModel(t));
        }
        
        return trainings;
    }
}