src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>The date and time when this training is expected to end.</description>
        <inlineHelpText>The date and time when this training is expected to end.</inlineHelpText>
        <label>End Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location where this training will take place.</description>
        <inlineHelpText>The location where this training will take place.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VolunteerTrainingAttendanceMapper_TEST.cls
@IsTest
private class VolunteerTrainingAttendanceMapper_TEST {
    
    private static Contact con;
    private static Volunteer_Training__c training;
    
    static {
        training = new Volunteer_Training__c(
            Description__c = 'testing',
            Location__c = 'my location',
            StartDateTime__c = Datetime.now().addDays(1),
            EndDateTime__c = Datetime.now().addDays(1).addMinutes(30)
        );
        insert training;
        
        con = new Contact(
            LastName = 'testcontact'
        );
        insert con;
    }
    
    @IsTest
    private static void testRoundTrip() {
        VolunteerTrainingAttendanceMapper mapper = VolunteerTrainingAttendanceMapper.getInstance();
        
        VolunteerTrainingViewModel vtvm = new VolunteerTrainingViewModel();
        vtvm.volunteerId = con.Id;
        vtvm.trainingId = training.Id;
        
        mapper.saveAttendance(new List<VolunteerTrainingViewModel>{vtvm});
        
        List<Volunteer_Training_Attendance__c> atts = [SELECT Id FROM Volunteer_Training_Attendance__c];
        System.assertEquals(1, atts.size());
        
        List<VolunteerTrainingViewModel> upcoming = mapper.getUpcomingAttendanceByVolunteerId(con.Id);
        System.assertEquals(1, upcoming.size());
        
        List<VolunteerTrainingViewModel> byId = mapper.getAttendanceByIds(new List<Id>{upcoming[0].id});
        System.assertEquals(1, byId.size());
        System.assertEquals(training.Id, byId[0].trainingId);
        
        mapper.deleteAttendance(new List<Id>{byId[0].id});
    
        List<Volunteer_Training_Attendance__c> afterDelete = new List<Volunteer_Training_Attendance__c>([
            SELECT Id FROM Volunteer_Training_Attendance__c
        ]);
        System.assert(afterDelete.isEmpty());
    }
    
}