src/objects/Volunteer_Training__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <description>The date and time when this training is expected to end.</description>
        <inlineHelpText>The date and time when this training is expected to end.</inlineHelpText>
        <label>End Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The location where this training will take place.</description>
        <inlineHelpText>The location where this training will take place.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <description>The date and time when this training starts.</description>
        <inlineHelpText>The date and time when this training starts.</inlineHelpText>
        <label>Start Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Volunteer Training</label>
    <nameField>
        <displayFormat>VT-{00000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volunteer_Training_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Training__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks if the volunteer attended and completed the training. If checked, the volunteer showed up and completed the training. If unchecked, the volunteer signed up but never completed the training.</description>
        <inlineHelpText>Did this volunteer attend and complete this training? If checked, the volunteer showed up and completed the training. If unchecked, the volunteer signed up but never completed the training.</inlineHelpText>
        <label>Completed Training</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Training__c</fullName>
        <label>Volunteer Training</label>
        <referenceTo>Volunteer_Training__c</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Training Attendances</relationshipLabel>
        <relationshipName>Volunteer_Training_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Training Attendance</label>
    <nameField>
        <displayFormat>VTA-{00000}</displayFormat>
        <label>Volunteer Training Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VolunteerTrainingAttendanceMapper.cls
public virtual without sharing class VolunteerTrainingAttendanceMapper {
    
    @TestVisible
    private static VolunteerTrainingAttendanceMapper instance;
    
    protected VolunteerTrainingAttendanceMapper() { }
    
    public static VolunteerTrainingAttendanceMapper getInstance() {
        if (instance != null) {
            return instance;
        }
    
        instance = new VolunteerTrainingAttendanceMapper();
        return instance;
    }
    
    public virtual List<VolunteerTrainingViewModel> getUpcomingAttendanceByVolunteerId(Id volunteerId) {
        String whereClause = ' WHERE Volunteer__c = \'' + volunteerId + '\'';
        whereClause += ' AND Volunteer_Training__r.StartDateTime__c > ' +
            Datetime.now().format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'') + ' ';
        
        return queryAttendance(whereClause);
    }
    
    public virtual List<VolunteerTrainingViewModel> getAttendanceByIds(List<Id> ids) {
        String idString = String.join(ids, '\', \'');
        String whereClause = ' WHERE Id IN (\'' + idString + '\') ';
        
        return queryAttendance(whereClause);
    }
    
    public virtual List<VolunteerTrainingViewModel> saveAttendance(List<VolunteerTrainingViewModel> attendances) {
        List<Volunteer_Training_Attendance__c> records = new List<Volunteer_Training_Attendance__c>();
        
        for (VolunteerTrainingViewModel a : attendances) {
            records.add(new Volunteer_Training_Attendance__c(
                Id = a.id,
                Completed_Training__c = (a.completed == true),
                Volunteer_Training__c = a.trainingId,
                Volunteer__c = a.volunteerId
            ));
        }
        
        if (records.isEmpty()) {
            return null;
        }
        
        upsert records;
    
        Map<Id, Volunteer_Training_Attendance__c> Idmap = new Map<Id, Volunteer_Training_Attendance__c>(records);
        List<Id> Idlist = new List<Id>();
        Idlist.addAll(Idmap.keySet());
        return getAttendanceByIds(Idlist);
    }
    
    public virtual void deleteAttendance(List<Id> ids) {
        List<Volunteer_Training_Attendance__c> records = new List<Volunteer_Training_Attendance__c>();
        
        for (Id id : ids) {
            records.add(new Volunteer_Training_Attendance__c(Id = id));
        }
        
        delete records;
    }
    
    private List<VolunteerTrainingViewModel> queryAttendance(String whereClause) {
        List<VolunteerTrainingViewModel> trainings;
        
        List<String> fields = new List<String>{
            'Id',
            'Completed_Training__c',
            'Volunteer__c',
            'Volunteer_Training__c',
            'Volunteer_Training__r.Description__c',
            'Volunteer_Training__r.EndDateTime__c',
            'Volunteer_Training__r.Location__c',
            'Volunteer_Training__r.StartDateTime__c'
        };
        
        String queryString = String.format(
            'SELECT {0} FROM Volunteer_Training_Attendance__c ',
            new List<String>{String.join(fields, ', ')}
        );
        
        if (String.isNotBlank(whereClause)) {
            queryString += whereClause;
        }
        
        queryString += ' ORDER BY Volunteer_Training__r.StartDateTime__c ASC ';
        
        for (Volunteer_Training_Attendance__c vta : Database.query(queryString)) {
            if (trainings == null) {
                trainings = new List<VolunteerTrainingViewModel>();
            }
            
            trainings.add(new VolunteerTrainingViewModel(vta));
        }
        
        
        return trainings;
    }
}